[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "tissue-properties"
version = "0.4.0"
description = "A python library for computing/looking up various tissue properties used in laser bioeffect models."
readme = "README.md"
authors = [
  { name = "CD Clark III", email = "clifton.clark@gmail.com" },
]
requires-python = ">=3.12"

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "numpy>=2",
  "pint>=0.24.4",
  "scipy>=1.14.1",
  "thefuzz>=0.22.1",
  "typer>=0.13.1",
]
scripts.tissue-properties = "tissue_properties.cli:app"

[dependency-groups]
dev = [
  "pytest>=8.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [ "src/tissue_properties" ]
